spring.application.name=webquiz

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=quiz
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG
server.servlet.session.timeout=30m