spring.application.name=webquiz

spring.mongodb.uri=mongodb://localhost:27017/quiz
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG
server.servlet.session.timeout=30m